Repository ibm-mas/ansible-devops, pull requests merged in 2023-04, with the labels that each got.

#752 [major] Switch to ARTIFACTORY_TOKEN
  Makefile
  docs/changes.md
  docs/playbooks/oneclick-core.md
  ibm/mas_devops/README.md
  ibm/mas_devops/galaxy.yml
  ibm/mas_devops/roles/convert_to_olm/README.md
  ibm/mas_devops/roles/convert_to_olm/defaults/main.yml
  ibm/mas_devops/roles/convert_to_olm/tasks/main.yml
  ibm/mas_devops/roles/ibm_catalogs/README.md
  ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/development-catalog.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/main.yml
  ibm/mas_devops/roles/install_operator/defaults/main.yml
  ibm/mas_devops/roles/install_operator/tasks/main.yml
  ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
  ibm/mas_devops/roles/mirror_case_prepare/defaults/main.yml
  ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-dev.yml
  ibm/mas_devops/roles/mirror_extras_prepare/defaults/main.yml
  ibm/mas_devops/roles/mirror_extras_prepare/tasks/catalog.yml
  ibm/mas_devops/roles/mirror_extras_prepare/vars/catalog.yml
  ibm/mas_devops/roles/mirror_images/defaults/main.yml
  ibm/mas_devops/roles/sls/README.md
  ibm/mas_devops/roles/suite_app_install/README.md
  ibm/mas_devops/roles/suite_install/README.md
Labels: High Priority

#735 [patch] Add support for GPU DRIVER VERSION environment var
  ibm/mas_devops/roles/nvidia_gpu/README.md
  ibm/mas_devops/roles/nvidia_gpu/defaults/main.yml
  ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
  ibm/mas_devops/roles/nvidia_gpu/templates/clusterpolicies/ocp_4.10.yml.j2
  ibm/mas_devops/roles/nvidia_gpu/templates/clusterpolicies/ocp_4.11.yml.j2
  ibm/mas_devops/roles/nvidia_gpu/templates/clusterpolicy.yml.j2
Labels: Improvement/Tweak

#748 [patch] Fixes for MongoCfg generation with existing IBMCloud MongoDb
  ibm/mas_devops/roles/mongodb/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/create-mongo-service-credentials.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/install.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/save-mongo-info.yml
  ibm/mas_devops/roles/mongodb/templates/ibm/mongo_admin_credentials_secret.yml.j2
  ibm/mas_devops/roles/mongodb/templates/ibm/suite_mongocfg.yml.j2
Labels: Bug Fix

#755 [major] Remove SBO support
  build/bin/copy-role-docs.sh
  docs/changes.md
  docs/playbooks/oneclick-core.md
  ibm/mas_devops/README.md
  ibm/mas_devops/playbooks/oneclick_core.yml
  ibm/mas_devops/roles/cluster_monitoring/meta/main.yml
  ibm/mas_devops/roles/sbo/README.md
  ibm/mas_devops/roles/sbo/defaults/main.yml
  ibm/mas_devops/roles/sbo/meta/main.yml
  ibm/mas_devops/roles/sbo/tasks/install/stable.yml
  ibm/mas_devops/roles/sbo/tasks/main.yml
  ibm/mas_devops/roles/sbo/templates/subscription-stable.yml
  ibm/mas_devops/roles/sbo_upgrade/README.md
  ibm/mas_devops/roles/sbo_upgrade/defaults/main.yml
  ibm/mas_devops/roles/sbo_upgrade/meta/main.yml
  ibm/mas_devops/roles/sbo_upgrade/tasks/main.yml
  ibm/mas_devops/roles/sbo_upgrade/tasks/sbo_upgrade/stable.yml
  ibm/mas_devops/roles/sbo_upgrade/tasks/sbo_upgrade/upgrade.yml
  ibm/mas_devops/roles/sbo_upgrade/tasks/sbo_upgrade/wait_for_spec_application.yml
  ibm/mas_devops/roles/sbo_upgrade/templates/blankcr.yml.j2
  ibm/mas_devops/roles/sbo_upgrade/templates/blanksecret.yml.j2
  ibm/mas_devops/roles/sbo_upgrade/templates/sbo/subscription-stable.yml
  mkdocs.yml
Labels: Enhancement

#756 [patch] Update all defaults for MAS 8.10
  docs/playbooks/oneclick-update.md
  ibm/mas_devops/playbooks/mirror_add_assist.yml
  ibm/mas_devops/playbooks/mirror_add_hputilities.yml
  ibm/mas_devops/playbooks/mirror_add_iot.yml
  ibm/mas_devops/playbooks/mirror_add_manage.yml
  ibm/mas_devops/playbooks/mirror_add_monitor.yml
  ibm/mas_devops/playbooks/mirror_add_optimizer.yml
  ibm/mas_devops/playbooks/mirror_add_predict.yml
  ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
  ibm/mas_devops/playbooks/mirror_core.yml
  ibm/mas_devops/playbooks/oneclick_add_assist.yml
  ibm/mas_devops/playbooks/oneclick_add_iot.yml
  ibm/mas_devops/playbooks/oneclick_add_manage.yml
  ibm/mas_devops/playbooks/oneclick_add_monitor.yml
  ibm/mas_devops/playbooks/oneclick_add_optimizer.yml
  ibm/mas_devops/playbooks/oneclick_add_predict.yml
  ibm/mas_devops/playbooks/oneclick_add_visualinspection.yml
  ibm/mas_devops/playbooks/oneclick_core.yml
  ibm/mas_devops/roles/ibm_catalogs/README.md
Labels: Improvement/Tweak

#761 [patch] Remove checks for nfd-master
  ibm/mas_devops/roles/nvidia_gpu/tasks/nfd_setup.yml
Labels: Improvement/Tweak
