Repository ibm-mas/ansible-devops, pull requests merged in 2023-05, with the labels that each got.

#799 [patch] Upload ansible-devops tar.gz to Artifactory
  .github/workflows/ansible.yml
  build/bin/.functions.sh
  build/bin/artifactory-release.sh
Labels: Improvement/Tweak

#807 [patch] Improve build system
  .github/workflows/ansible.yml
  build/bin/artifactory-release.sh
Labels: Bug Fix

#822 [patch] Fix docDb role readme and remove unrequired vars
  ibm/mas_devops/roles/aws_documentdb_user/README.md
  ibm/mas_devops/roles/aws_documentdb_user/defaults/main.yml
  ibm/mas_devops/roles/aws_documentdb_user/tasks/main.yml
  ibm/mas_devops/roles/mongodb/README.md
  ibm/mas_devops/roles/mongodb/tasks/providers/aws/install.yml
Labels: Bug Fix

#813 [minor] Support May Catalog update
  docs/changes.md
  docs/playbooks/oneclick-update.md
  ibm/mas_devops/README.md
  ibm/mas_devops/common_vars/casebundles/v8-230518-amd64.yml
  ibm/mas_devops/common_vars/digests/ibm-mas-manage/8.4.9.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-manage/8.5.5.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-manage/8.6.1.yaml
  ibm/mas_devops/playbooks/mirror_add_assist.yml
  ibm/mas_devops/playbooks/mirror_add_hputilities.yml
  ibm/mas_devops/playbooks/mirror_add_iot.yml
  ibm/mas_devops/playbooks/mirror_add_manage.yml
  ibm/mas_devops/playbooks/mirror_add_monitor.yml
  ibm/mas_devops/playbooks/mirror_add_optimizer.yml
  ibm/mas_devops/playbooks/mirror_add_predict.yml
  ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
  ibm/mas_devops/playbooks/mirror_core.yml
  ibm/mas_devops/playbooks/oneclick_update.yml
Labels: Catalog Update
