Repository ibm-mas/ansible-devops, pull requests merged in 2023-07, with the labels that each got.

#892 [patch] Add let's encrypt root cert to ocs config yaml
  ibm/mas_devops/roles/cos/templates/ibm/objectstoragecfg.yml.j2
  ibm/mas_devops/roles/cos/templates/ocs/objectstoragecfg.yml.j2
  ibm/mas_devops/roles/uds/templates/bascfg.yml.j2
Labels: Bug Fix

#891 [patch] Update for airgap pre-release
  ibm/mas_devops/common_vars/casebundles/v8-airgap-amd64.yml
  ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Labels: Air Gap, Improvement/Tweak

#889 [patch] Fix FYRE API provision/deprovision logic
  ibm/mas_devops/roles/ocp_deprovision/tasks/providers/fyre.yml
  ibm/mas_devops/roles/ocp_provision/tasks/providers/fyre.yml
Labels: Bug Fix

#885 [patch] Improve documentation for contributors
  CONTRIBUTING.md
  README.md
  ibm/mas_devops/roles/cp4d/README.md
  ibm/mas_devops/roles/cp4d_service/README.md
  ibm/mas_devops/roles/ocp_upgrade/README.md
Labels: Documentation Update

#780 [minor] Support setting trustDefaultCAs in Suite
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/suite_install/README.md
  ibm/mas_devops/roles/suite_install/defaults/main.yml
  ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Labels: Enhancement

#901 [minor] Support customizable EFS storage ID
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/ocp_efs/README.md
  ibm/mas_devops/roles/ocp_efs/defaults/main.yml
  ibm/mas_devops/roles/ocp_efs/tasks/efs-setup.yml
  ibm/mas_devops/roles/ocp_efs/templates/efs-csi-storage-class.yml.j2
Labels: Enhancement

#902 [minor] Support customizable AWS MSK secret name
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/kafka/README.md
  ibm/mas_devops/roles/kafka/defaults/main.yaml
Labels: Enhancement

#907 [patch] Add missing ocp_efs doc
  build/bin/copy-role-docs.sh
  mkdocs.yml
Labels: Documentation Update

#908 [patch] Fix CP4D_X env var naming (should be CPD_X)
  ibm/mas_devops/playbooks/oneclick_add_manage.yml
Labels: Documentation Update

#911 [patch] More dbm_config cleanup
  ibm/mas_devops/roles/db2/defaults/main.yml
Labels: Bug Fix

#912 [patch] Fix use of incorrect quotes inside jinja block
  ibm/mas_devops/roles/db2/defaults/main.yml
Labels: Bug Fix

#920 [patch] Fix Turbonomic secret field names
  ibm/mas_devops/roles/kubeturbo/templates/turbonomic-secret.yml.j2
Labels: Bug Fix

#921 [patch] Fix uninstall
  ibm/mas_devops/roles/suite_uninstall/tasks/main.yml
Labels: Bug Fix
