Repository ibm-mas/ansible-devops, pull requests merged in 2023-01, with the labels that each got.

#575 [minor] AWS support for S3 buckets, Manage logging and imported certificates
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/aws_bucket_access_point/README.md
  ibm/mas_devops/roles/aws_bucket_access_point/defaults/main.yml
  ibm/mas_devops/roles/aws_bucket_access_point/files/ap-policy.json.j2
  ibm/mas_devops/roles/aws_bucket_access_point/meta/main.yml
  ibm/mas_devops/roles/aws_bucket_access_point/tasks/main.yml
  ibm/mas_devops/roles/aws_policy/README.md
  ibm/mas_devops/roles/aws_policy/defaults/main.yml
  ibm/mas_devops/roles/aws_policy/files/policy-template-sample.json
  ibm/mas_devops/roles/aws_policy/meta/main.yml
  ibm/mas_devops/roles/aws_policy/tasks/create-policy-from-json-file.yml
  ibm/mas_devops/roles/aws_policy/tasks/create-policy-from-variable.yml
  ibm/mas_devops/roles/aws_policy/tasks/main.yml
  ibm/mas_devops/roles/aws_user_creation/README.md
  ibm/mas_devops/roles/aws_user_creation/defaults/main.yml
  ibm/mas_devops/roles/aws_user_creation/meta/main.yml
  ibm/mas_devops/roles/aws_user_creation/tasks/main.yml
  ibm/mas_devops/roles/cos_bucket/README.md
  ibm/mas_devops/roles/cos_bucket/defaults/main.yml
  ibm/mas_devops/roles/cos_bucket/tasks/main.yml
  ibm/mas_devops/roles/cos_bucket/tasks/providers/aws/create.yml
  ibm/mas_devops/roles/cos_bucket/tasks/providers/aws/delete.yml
  ibm/mas_devops/roles/cos_bucket/tasks/providers/ibm/create.yml
  ibm/mas_devops/roles/cos_bucket/tasks/providers/ibm/create_service_credentials.yml
  ibm/mas_devops/roles/cos_bucket/tasks/providers/ibm/delete.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/README.md
  ibm/mas_devops/roles/suite_manage_import_certs_config/defaults/main.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/files/manage-certs-sample.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/meta/main.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/tasks/main.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/tasks/manage-certs-from-file.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/tasks/manage-certs-from-variable.yml
  ibm/mas_devops/roles/suite_manage_import_certs_config/templates/imported-certs.yml.j2
  ibm/mas_devops/roles/suite_manage_logging_config/README.md
  ibm/mas_devops/roles/suite_manage_logging_config/defaults/main.yml
  ibm/mas_devops/roles/suite_manage_logging_config/tasks/main.yml
  ibm/mas_devops/roles/suite_manage_logging_config/tasks/providers/aws/setup-manage-logging.yml
  ibm/mas_devops/roles/suite_manage_logging_config/tasks/providers/cos/retrieve-cos-certs.yml
  ibm/mas_devops/roles/suite_manage_logging_config/tasks/retrieve-cos-certs.yml
  ibm/mas_devops/roles/suite_manage_logging_config/tasks/setup-manage-logging.yml
  ibm/mas_devops/roles/suite_manage_logging_config/templates/imported-certs.yml.j2
  ibm/mas_devops/roles/suite_manage_logging_config/templates/logging-bucket-creds.yml.j2
  mkdocs.yml
Labels: Enhancement

#524 [minor] Support switch MAS legacy install to OLM
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/suite_install/README.md
  ibm/mas_devops/roles/suite_switch_to_olm/README.md
  ibm/mas_devops/roles/suite_switch_to_olm/defaults/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/meta/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/tasks/ibm-common-services.yml
  ibm/mas_devops/roles/suite_switch_to_olm/tasks/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/templates/operator-group.yml.j2
  ibm/mas_devops/roles/suite_switch_to_olm/templates/subscription.yml.j2
  mkdocs.yml
Labels: Enhancement

#549 [minor] Support management of CIS in IBM Cloud
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/cis/README.md
  ibm/mas_devops/roles/cis/defaults/main.yml
  ibm/mas_devops/roles/cis/meta/main.yml
  ibm/mas_devops/roles/cis/tasks/main.yml
  ibm/mas_devops/roles/cis/tasks/provider/ibm/deprovision.yml
  ibm/mas_devops/roles/cis/tasks/provider/ibm/provision.yml
  ibm/mas_devops/roles/cis/templates/cis_output.yml.j2
  mkdocs.yml
Labels: Enhancement

#588 [patch] Fix support for Mongo certificates in SLS install
  ibm/mas_devops/roles/sls/README.md
  ibm/mas_devops/roles/sls/tasks/gencfg/main.yml
  ibm/mas_devops/roles/sls/tasks/install/bootstrap.yml
  ibm/mas_devops/roles/sls/tasks/install/install_digest_cm.yml
  ibm/mas_devops/roles/sls/tasks/install/main.yml
  ibm/mas_devops/roles/sls/tasks/install/sls-verify.yml
  ibm/mas_devops/roles/sls/tasks/main.yml
  ibm/mas_devops/roles/sls/templates/licenseservice.yml.j2
  ibm/mas_devops/roles/sls/templates/mongo-certificates.yml.j2
Labels: Enhancement

#599 [patch] Make ocp_upgrade flexible enough to upgrade any ocp_version
  ibm/mas_devops/roles/cis/tasks/provider/ibm/deprovision.yml
  ibm/mas_devops/roles/ocp_upgrade/README.md
  ibm/mas_devops/roles/ocp_upgrade/defaults/main.yml
  ibm/mas_devops/roles/ocp_upgrade/tasks/main.yml
  ibm/mas_devops/roles/ocp_upgrade/tasks/ocp_upgrade.yml
  ibm/mas_devops/roles/ocp_upgrade/tasks/wait_workers_upgrade.yml
Labels: Improvement/Tweak

#576 [patch] refine setupdb.sh reviewed by DBA
  ibm/mas_devops/roles/suite_db2_setup_for_manage/README.md
  ibm/mas_devops/roles/suite_db2_setup_for_manage/defaults/main.yml
  ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
  ibm/mas_devops/roles/suite_db2_setup_for_manage/templates/setupdb.sh.j2
Labels: Improvement/Tweak

#605 [patch] Increase CertManagerController CPU limit
  ibm/mas_devops/roles/cert_manager/tasks/main.yml
  ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
  ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
Labels: Bug Fix

#603 [patch] Enhancing CIS domain security in suite_dns
  .gitignore
  docs/changes.md
  ibm/mas_devops/plugins/modules/cis_dns_entries.py
  ibm/mas_devops/roles/cis/tasks/provider/ibm/deprovision.yml
  ibm/mas_devops/roles/suite_dns/README.md
  ibm/mas_devops/roles/suite_dns/defaults/main.yaml
  ibm/mas_devops/roles/suite_dns/tasks/main.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_dns_mgmt.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_domain_setting.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_edge_certificate.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_waf_rule.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/cis_webhook.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cis/main.yml
  ibm/mas_devops/roles/suite_dns/tasks/providers/cloudflare/main.yml
  ibm/mas_devops/roles/suite_dns/templates/routes_edge_certificates.txt.j2
  ibm/mas_devops/roles/suite_dns/vars/dnsentries.yml
  ibm/mas_devops/roles/suite_dns/vars/edge_certificate_routes.yml
  ibm/mas_devops/roles/suite_dns/vars/waf_rules_to_disable.yml
Labels: Improvement/Tweak

#593 [patch] Predict CRD updates
  docs/playbooks/oneclick-predict.md
  ibm/mas_devops/playbooks/oneclick_add_predict.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/predict.yml
  ibm/mas_devops/roles/suite_app_config/vars/predict.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/predict.yml
  ibm/mas_devops/roles/suite_app_install/vars/predict.yml
  mkdocs.yml
Labels: Bug Fix

#608 [patch] Update cert-manager sizing call
  ibm/mas_devops/roles/cert_manager/tasks/main.yml
  ibm/mas_devops/roles/cert_manager/templates/ibm-cert-manager-common-service.yml
Labels: Bug Fix

#609 [patch] Increase retry count on ROKS image registry PVC lookup
  ibm/mas_devops/roles/ocp_roks_upgrade_registry_storage/tasks/main.yml
Labels: Improvement/Tweak

#598 [minor] Support VPC creation or deletion in AWS Cloud
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/aws_vpc/README.md
  ibm/mas_devops/roles/aws_vpc/defaults/main.yml
  ibm/mas_devops/roles/aws_vpc/meta/main.yml
  ibm/mas_devops/roles/aws_vpc/tasks/deprovision.yml
  ibm/mas_devops/roles/aws_vpc/tasks/main.yml
  ibm/mas_devops/roles/aws_vpc/tasks/provision.yml
  ibm/mas_devops/roles/aws_vpc/templates/vpc_configmap.yml.j2
  mkdocs.yml
Labels: Enhancement

#591 [minor] Support updating admin password for CP4D instance
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/cp4d_admin_pwd_update/README.md
  ibm/mas_devops/roles/cp4d_admin_pwd_update/defaults/main.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/meta/main.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/tasks/cp4d-access-control.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/tasks/get-cp4d-bearer-token.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/tasks/get-cp4d-route.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/tasks/main.yml
  ibm/mas_devops/roles/cp4d_admin_pwd_update/templates/cp4d_admin_credentials_secret.yaml.j2
  mkdocs.yml
Labels: Enhancement

#600 [minor] Add JDBC configuration to connect to external databases
  docs/changes.md
  docs/playbooks/oneclick-manage.md
  ibm/mas_devops/README.md
  ibm/mas_devops/playbooks/oneclick_add_manage.yml
  ibm/mas_devops/roles/gencfg_jdbc/README.md
  ibm/mas_devops/roles/gencfg_jdbc/tasks/main.yml
  ibm/mas_devops/roles/gencfg_jdbc/templates/jdbccfg.yml.j2
  ibm/mas_devops/roles/suite_app_config/README.md
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
  ibm/mas_devops/roles/suite_app_config/vars/health.yml
  ibm/mas_devops/roles/suite_app_config/vars/manage.yml
Labels: Enhancement

#621 [patch] Doc updates for new automation operator install
  docs/index.md
Labels: Documentation Update

#618 [patch] Add retry to packagemanifest lookup in common_services role
  ibm/mas_devops/roles/common_services/tasks/main.yml
Labels: Improvement/Tweak
