Repository ibm-mas/ansible-devops, pull requests merged in 2023-02, with the labels that each got.

#595 [patch] Add skip_compatibility_check for upgrade error path test
  ibm/mas_devops/roles/suite_app_upgrade/README.md
  ibm/mas_devops/roles/suite_app_upgrade/defaults/main.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/check_app_compatibility.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/check_core_compatibility.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/main.yml
  ibm/mas_devops/roles/suite_upgrade/README.md
  ibm/mas_devops/roles/suite_upgrade/defaults/main.yml
  ibm/mas_devops/roles/suite_upgrade/tasks/check_app_compatibility.yml
  ibm/mas_devops/roles/suite_upgrade/tasks/check_core_compatibility.yml
  ibm/mas_devops/roles/suite_upgrade/tasks/main.yml
Labels: Improvement/Tweak

#637 [minor] Support uninstall of Core & dependencies
  build/bin/copy-role-docs.sh
  docs/changes.md
  docs/playbooks/uninstall-core.md
  ibm/mas_devops/README.md
  ibm/mas_devops/playbooks/uninstall_core.yml
  ibm/mas_devops/roles/cert_manager/README.md
  ibm/mas_devops/roles/cert_manager/defaults/main.yml
  ibm/mas_devops/roles/cert_manager/tasks/actions/install.yml
  ibm/mas_devops/roles/cert_manager/tasks/actions/uninstall.yml
  ibm/mas_devops/roles/cert_manager/tasks/main.yml
  ibm/mas_devops/roles/cluster_monitoring/README.md
  ibm/mas_devops/roles/cluster_monitoring/defaults/main.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/install/determine-storage-classes.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/install/grafana.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/install/main.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/main.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/grafana.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/uninstall/main.yml
  ibm/mas_devops/roles/cluster_monitoring/templates/cluster-monitoring.yml.j2
  ibm/mas_devops/roles/common_services/README.md
  ibm/mas_devops/roles/common_services/defaults/main.yml
  ibm/mas_devops/roles/common_services/tasks/actions/install.yml
  ibm/mas_devops/roles/common_services/tasks/actions/uninstall.yml
  ibm/mas_devops/roles/common_services/tasks/main.yml
  ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/development-catalog.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/main.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/update-digest-maps.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/main.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/uninstall/main.yml
  ibm/mas_devops/roles/mongodb/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/community/install.yml
  ibm/mas_devops/roles/mongodb/tasks/community/uninstall.yml
  ibm/mas_devops/roles/mongodb/tasks/main.yml
  ibm/mas_devops/roles/sls/README.md
  ibm/mas_devops/roles/sls/defaults/main.yml
  ibm/mas_devops/roles/sls/tasks/install/main.yml
  ibm/mas_devops/roles/sls/tasks/main.yml
  ibm/mas_devops/roles/sls/tasks/uninstall/main.yml
  ibm/mas_devops/roles/suite_install/defaults/main.yml
  ibm/mas_devops/roles/suite_install/tasks/main.yml
  ibm/mas_devops/roles/suite_uninstall/README.md
  ibm/mas_devops/roles/suite_uninstall/defaults/main.yml
  ibm/mas_devops/roles/suite_uninstall/meta/main.yml
  ibm/mas_devops/roles/suite_uninstall/tasks/main.yml
  ibm/mas_devops/roles/uds/README.md
  ibm/mas_devops/roles/uds/defaults/main.yml
  ibm/mas_devops/roles/uds/tasks/install/main.yml
  ibm/mas_devops/roles/uds/tasks/main.yml
  ibm/mas_devops/roles/uds/tasks/uninstall/main.yml
  mkdocs.yml
Labels: Enhancement

#635 [minor] Support SLS workload scaling feature
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/sls/README.md
  ibm/mas_devops/roles/sls/defaults/main.yml
  ibm/mas_devops/roles/sls/tasks/install/main.yml
  ibm/mas_devops/roles/sls/templates/licenseservice.yml.j2
Labels: Enhancement

#626 [minor] Support creating and deleting IBM Cloud resource keys
  .gitignore
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/ibmcloud_resource_key/README.md
  ibm/mas_devops/roles/ibmcloud_resource_key/defaults/main.yml
  ibm/mas_devops/roles/ibmcloud_resource_key/meta/main.yml
  ibm/mas_devops/roles/ibmcloud_resource_key/tasks/main.yml
  ibm/mas_devops/roles/ibmcloud_resource_key/tasks/service_key_create.yml
  ibm/mas_devops/roles/ibmcloud_resource_key/tasks/service_key_delete.yml
Labels: Enhancement

#640 [patch] Fixes to support no/single/dual Db2 MAS install
  ibm/mas_devops/playbooks/oneclick_add_assist.yml
  ibm/mas_devops/roles/appconnect/tasks/appconnectcfg.yml
  ibm/mas_devops/roles/cis/tasks/provider/ibm/provision.yml
  ibm/mas_devops/roles/cos/tasks/providers/ibm/provision.yml
  ibm/mas_devops/roles/cos/tasks/providers/ocs/provision.yml
  ibm/mas_devops/roles/cp4d_service/tasks/gencfg/gencfg-wd.yml
  ibm/mas_devops/roles/cp4d_service/tasks/gencfg/gencfg-wsl.yml
  ibm/mas_devops/roles/db2/README.md
  ibm/mas_devops/roles/db2/tasks/suite_jdbccfg.yml
  ibm/mas_devops/roles/gencfg_jdbc/tasks/main.yml
  ibm/mas_devops/roles/gencfg_watsonstudio/tasks/main.yml
  ibm/mas_devops/roles/gencfg_workspace/tasks/main.yml
  ibm/mas_devops/roles/install_operator/tasks/main.yml
  ibm/mas_devops/roles/kafka/tasks/main.yaml
  ibm/mas_devops/roles/mongodb/tasks/community/install.yml
  ibm/mas_devops/roles/sls/tasks/gencfg/main.yml
  ibm/mas_devops/roles/sls/tasks/install/main.yml
  ibm/mas_devops/roles/suite_app_config/README.md
  ibm/mas_devops/roles/suite_app_config/defaults/main.yml
  ibm/mas_devops/roles/suite_app_config/tasks/main.yml
  ibm/mas_devops/roles/suite_app_config/templates/workspace.yml.j2
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/assist.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/hputilities.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/iot.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/monitor.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/mso.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/optimizer.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/predict.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/safety.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/visualinspection.yml
  ibm/mas_devops/roles/suite_app_install/README.md
  ibm/mas_devops/roles/suite_app_install/defaults/main.yml
  ibm/mas_devops/roles/suite_app_install/tasks/main.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/iot.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/predict.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/safety.yml
  ibm/mas_devops/roles/suite_install/tasks/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/tasks/main.yml
  ibm/mas_devops/roles/uds/tasks/gencfg/main.yml
Labels: Bug Fix, Improvement/Tweak

#643 [patch] Improved Db2 role debug
  ibm/mas_devops/roles/db2/tasks/main.yml
Labels: Improvement/Tweak

#644 [patch] Multiple Db2 role bug fixes
  ibm/mas_devops/roles/db2/README.md
  ibm/mas_devops/roles/db2/defaults/main.yml
  ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
Labels: Bug Fix, Db2

#648 [patch] Pick up mongodb 4.2.23
  ibm/mas_devops/roles/mongodb/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/community/install.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.0/cr.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.0/crd.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.0/manager.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.0/rbac.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.8/cr.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.8/crd.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.8/manager.yml
  ibm/mas_devops/roles/mongodb/templates/community/0.7.8/rbac.yml
  ibm/mas_devops/roles/sls/defaults/main.yml
Labels: Improvement/Tweak
