Repository ibm-mas/ansible-devops, pull requests merged in 2023-06, with the labels that each got.

#840 [patch] Exclusive workaround for Monitor mirroring
  ibm/mas_devops/common_vars/digests/ibm-data-dictionary/1.1.4.yaml
  ibm/mas_devops/playbooks/mirror_add_monitor.yml
  ibm/mas_devops/roles/suite_app_install/tasks/monitor.yml
Labels: Air Gap, Bug Fix

#848 [patch] Dynamically detect catalog sources
  ibm/mas_devops/.oc-mirror.log
  ibm/mas_devops/roles/cluster_monitoring/tasks/install/grafana.yml
  ibm/mas_devops/roles/cluster_monitoring/tasks/install/opentelemetry.yml
  ibm/mas_devops/roles/cluster_monitoring/templates/grafana-subscription.yml.j2
  ibm/mas_devops/roles/cluster_monitoring/templates/opentelemetry-subscription.yaml
  ibm/mas_devops/roles/kafka/tasks/provider/redhat/install.yml
  ibm/mas_devops/roles/kafka/templates/redhat/subscription.yml.j2
  ibm/mas_devops/roles/kubeturbo/tasks/main.yml
  ibm/mas_devops/roles/kubeturbo/templates/kubeturbo-subscription.yaml
  ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
  ibm/mas_devops/roles/nvidia_gpu/tasks/main.yml
  ibm/mas_devops/roles/nvidia_gpu/tasks/nfd_setup.yml
  ibm/mas_devops/roles/nvidia_gpu/templates/gpu-subscription.yml.j2
  ibm/mas_devops/roles/nvidia_gpu/templates/nfd-subscription.yml.j2
  ibm/mas_devops/roles/ocp_efs/tasks/main.yml
  ibm/mas_devops/roles/ocp_efs/templates/efs-csi-subscription.yml.j2
  ibm/mas_devops/roles/ocs/tasks/localstorage.yml
  ibm/mas_devops/roles/ocs/tasks/main.yml
  ibm/mas_devops/roles/ocs/templates/localstorage/subscription.yaml
  ibm/mas_devops/roles/ocs/templates/storage/subscription.yaml
  ibm/mas_devops/roles/suite_app_install/tasks/monitor.yml
  ibm/mas_devops/roles/uds/tasks/install/main.yml
  ibm/mas_devops/roles/uds/templates/crunchy-postgres/subscription.yml
Labels: Air Gap, Improvement/Tweak

#849 [patch] Fix amqstreams_defauilt_channel typo
  ibm/mas_devops/roles/kafka/tasks/provider/redhat/install.yml
Labels: Bug Fix

#854 [minor] Support OCP node configuration
  build/bin/copy-role-docs.sh
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/db2/README.md
  ibm/mas_devops/roles/db2/defaults/main.yml
  ibm/mas_devops/roles/db2/tasks/main.yml
  ibm/mas_devops/roles/db2/tasks/setup_norootsquash.yml
  ibm/mas_devops/roles/db2/templates/db2ucluster.yml.j2
  ibm/mas_devops/roles/ocp_node_config/README.md
  ibm/mas_devops/roles/ocp_node_config/defaults/main.yml
  ibm/mas_devops/roles/ocp_node_config/meta/main.yml
  ibm/mas_devops/roles/ocp_node_config/tasks/main.yml
  ibm/mas_devops/roles/suite_verify/tasks/main.yml
  mkdocs.yml
Labels: Enhancement

#857 [patch] Fix digest management issues for pre-OM1.6 operators
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.6.6.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas/8.9.5.yaml
  ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml
  ibm/mas_devops/roles/suite_app_install/tasks/monitor.yml
  ibm/mas_devops/roles/suite_install/tasks/install_digest_cm.yml
  ibm/mas_devops/roles/suite_install_digest_cm/tasks/main.yml
Labels: Air Gap, Bug Fix

#823 [patch] Add tags to the extras mirror manifest files
  ibm/mas_devops/roles/mirror_extras_prepare/README.md
  ibm/mas_devops/roles/mirror_extras_prepare/templates/direct.txt.j2
  ibm/mas_devops/roles/mirror_extras_prepare/templates/from-filesystem.txt.j2
  ibm/mas_devops/roles/mirror_extras_prepare/templates/to-filesystem.txt.j2
  ibm/mas_devops/roles/mirror_extras_prepare/vars/db2u_1.0.0.yml
  ibm/mas_devops/roles/mirror_extras_prepare/vars/db2u_1.0.1.yml
Labels: Air Gap, Bug Fix

#864 [patch] Create working dir if missing
  ibm/mas_devops/roles/mirror_extras_prepare/tasks/extras.yml
Labels: Bug Fix

#847 [patch] fix mas_app_channel when called via oneclick_upgrade playbook
  ibm/mas_devops/common_vars/application_info.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/check_app_compatibility.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/check_core_compatibility.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/main.yml
  ibm/mas_devops/roles/suite_app_upgrade/tasks/upgrade.yml
Labels: Bug Report, Triage, Customer Support Ticket

#875 [patch] Add missing MVI digests for airgap
  ibm/mas_devops/common_vars/digests/ibm-mas-visualinspection/8.7.1.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-visualinspection/8.8.1.yaml
Labels: Air Gap, Bug Fix

#876 [patch] Add edgeconfig.iot and edgeconfigapi.iot routes
  ibm/mas_devops/roles/suite_certs/templates/dnsentries.yml.j2
  ibm/mas_devops/roles/suite_dns/tasks/providers/cloudflare/main.yml
  ibm/mas_devops/roles/suite_dns/templates/dnsentries.yml.j2
  ibm/mas_devops/roles/suite_dns/templates/edge_certificate_routes.yml.j2
Labels: Improvement/Tweak

#881 [patch] Update Predict 8.9 documentation for playbook deployment #14825
  docs/playbooks/oneclick-predict.md
Labels: Documentation Update

#888 [patch] Fix UDS uninstall
  ibm/mas_devops/roles/uds/tasks/uninstall/main.yml
Labels: Bug Fix

#886 [minor] add support for 230627 catalog and MAS 8.9.7
  Makefile
  docs/changes.md
  docs/playbooks/oneclick-update.md
  ibm/mas_devops/README.md
  ibm/mas_devops/common_vars/casebundles/v8-230627-amd64.yml
  ibm/mas_devops/common_vars/digests/ibm-mas/8.9.7.yaml
  ibm/mas_devops/galaxy.yml
  ibm/mas_devops/playbooks/mirror_add_assist.yml
  ibm/mas_devops/playbooks/mirror_add_hputilities.yml
  ibm/mas_devops/playbooks/mirror_add_iot.yml
  ibm/mas_devops/playbooks/mirror_add_manage.yml
  ibm/mas_devops/playbooks/mirror_add_monitor.yml
  ibm/mas_devops/playbooks/mirror_add_optimizer.yml
  ibm/mas_devops/playbooks/mirror_add_predict.yml
  ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
  ibm/mas_devops/playbooks/mirror_core.yml
  ibm/mas_devops/playbooks/oneclick_update.yml
Labels: Catalog Update
