Repository ibm-mas/ansible-devops, pull requests merged in 2023-03, with the labels that each got.

#623 [minor] Support backup and restore for IBM MongoDB
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/mongodb/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/backup.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/restore.yml
  ibm/mas_devops/roles/mongodb/templates/ibm/backupid-template.yml.j2
Labels: Enhancement

#696 [patch] Fix attachments config for Health Standalone
  ibm/mas_devops/roles/cp4d/tasks/create-subscriptions.yml
  ibm/mas_devops/roles/db2/tasks/rotate_ldap_user_password.yml
  ibm/mas_devops/roles/kafka/tasks/provider/ibm/create-eventstreams-service-credentials.yml
  ibm/mas_devops/roles/suite_manage_attachments_config/defaults/main.yml
  ibm/mas_devops/roles/suite_manage_attachments_config/tasks/main.yml
  ibm/mas_devops/roles/suite_manage_attachments_config/tasks/wait_bundle_pods.yml
  ibm/mas_devops/roles/suite_manage_bim_config/defaults/main.yml
  ibm/mas_devops/roles/suite_manage_bim_config/tasks/main.yml
Labels: Improvement/Tweak

#699 [minor] Add support for March 2023 catalog
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/common_vars/casebundles/v8-230314-amd64.yml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.5.6.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.5.7.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.5.8.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.6.2.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.6.3.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-iot/8.6.4.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-manage/8.4.7.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-manage/8.5.3.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas-monitor/8.9.4.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas/8.8.7.yaml
  ibm/mas_devops/common_vars/digests/ibm-mas/8.9.3.yaml
  ibm/mas_devops/playbooks/mirror_add_assist.yml
  ibm/mas_devops/playbooks/mirror_add_iot.yml
  ibm/mas_devops/playbooks/mirror_add_manage.yml
  ibm/mas_devops/playbooks/mirror_add_monitor.yml
  ibm/mas_devops/playbooks/mirror_add_optimizer.yml
  ibm/mas_devops/playbooks/mirror_add_predict.yml
  ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
  ibm/mas_devops/playbooks/mirror_core.yml
  ibm/mas_devops/playbooks/oneclick_update.yml
Labels: Catalog Update

#702 [patch] Document UDS_ACTION values for suds (un)install
  ibm/mas_devops/roles/uds/README.md
Labels: Documentation Update

#691 [minor] Add OLM conversion role & playbook
  build/bin/copy-role-docs.sh
  ibm/mas_devops/playbooks/oneclick_convert_to_olm.yml
  ibm/mas_devops/roles/convert_to_olm/README.md
  ibm/mas_devops/roles/convert_to_olm/defaults/main.yml
  ibm/mas_devops/roles/convert_to_olm/meta/main.yml
  ibm/mas_devops/roles/convert_to_olm/tasks/ibm-common-services.yml
  ibm/mas_devops/roles/convert_to_olm/tasks/main.yml
  ibm/mas_devops/roles/convert_to_olm/templates/operator-group.yml.j2
  ibm/mas_devops/roles/convert_to_olm/templates/subscription.yml.j2
  ibm/mas_devops/roles/suite_switch_to_olm/README.md
  ibm/mas_devops/roles/suite_switch_to_olm/defaults/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/tasks/main.yml
  ibm/mas_devops/roles/suite_switch_to_olm/templates/operator-group.yml.j2
  ibm/mas_devops/roles/suite_switch_to_olm/templates/subscription.yml.j2
  mkdocs.yml
Labels: Enhancement

#716 [patch] Increase wait time for ManageWorkspace Ready
  ibm/mas_devops/roles/suite_app_config/vars/manage.yml
Labels: Improvement/Tweak

#703 [patch] Fix mqttBroker storage class and size configuration for IoT
  CONTRIBUTING.md
  ibm/mas_devops/roles/suite_app_install/README.md
  ibm/mas_devops/roles/suite_app_install/defaults/main.yml
  ibm/mas_devops/roles/suite_app_install/tasks/iot.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/iot.yml
Labels: Bug Fix

#710 [minor] Support setting imagePullPolicy in Suite
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/cluster_monitoring/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/backup.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/restore.yml
  ibm/mas_devops/roles/suite_app_install/vars/defaultspecs/iot.yml
  ibm/mas_devops/roles/suite_install/README.md
  ibm/mas_devops/roles/suite_install/defaults/main.yml
  ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Labels: Enhancement

#614 [minor] Add support for pre-release versions in airgap
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/common_vars/casebundles/v8-airgap-amd64.yml
  ibm/mas_devops/playbooks/mirror_add_visualinspection.yml
  ibm/mas_devops/roles/ibm_catalogs/defaults/main.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/development-catalog.yml
  ibm/mas_devops/roles/ibm_catalogs/tasks/install/main.yml
  ibm/mas_devops/roles/ibm_catalogs/templates/development-catalog-with-digest.yml.j2
  ibm/mas_devops/roles/install_operator/templates/ibm-entitlement-with-artifactory.json.j2
  ibm/mas_devops/roles/mirror_case_prepare/defaults/main.yml
  ibm/mas_devops/roles/mirror_case_prepare/tasks/main.yml
  ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-dev.yml
  ibm/mas_devops/roles/mirror_case_prepare/tasks/prepare-released.yml
  ibm/mas_devops/roles/mirror_extras_prepare/defaults/main.yml
  ibm/mas_devops/roles/mirror_extras_prepare/tasks/catalog.yml
  ibm/mas_devops/roles/mirror_extras_prepare/vars/catalog.yml
  ibm/mas_devops/roles/mirror_images/defaults/main.yml
  ibm/mas_devops/roles/mirror_images/templates/auth-secret.json.j2
  ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/imagecontentsourcepolicy.yml.j2
  ibm/mas_devops/roles/sls/tasks/install/install_digest_cm.yml
  ibm/mas_devops/roles/suite_app_install/tasks/install_digest_cm.yml
  ibm/mas_devops/roles/suite_install/tasks/install_digest_cm.yml
Labels: Enhancement

#731 [patch] Fix Manage one-click playbook documentation
  docs/playbooks/oneclick-manage.md
Labels: Documentation Update

#737 [patch] Add new codeowners
  .github/CODEOWNERS
Labels: Improvement/Tweak

#713 [patch] changes to fix DB21015E + SQL1032N
  ibm/mas_devops/roles/suite_db2_setup_for_manage/tasks/main.yml
Labels: AWS (IPI), Db2

#740 [minor] Mustgather role enhanced to collect certificates and other namespaces
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/suite_mustgather/README.md
  ibm/mas_devops/roles/suite_mustgather/defaults/main.yml
  ibm/mas_devops/roles/suite_mustgather/tasks/main.yml
Labels: Enhancement

#528 [minor] Add support of SSH public key in ocp_provision role
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/ocp_provision/README.md
  ibm/mas_devops/roles/ocp_provision/defaults/main.yml
  ibm/mas_devops/roles/ocp_provision/templates/ipi/install-config.yaml.j2
Labels: Enhancement

#706 [minor] Add MongoDb clean option to suite_uninstall role
  docs/changes.md
  ibm/mas_devops/README.md
  ibm/mas_devops/roles/mongodb/defaults/main.yml
  ibm/mas_devops/roles/mongodb/tasks/providers/ibm/backup.yml
  ibm/mas_devops/roles/suite_uninstall/README.md
  ibm/mas_devops/roles/suite_uninstall/defaults/main.yml
  ibm/mas_devops/roles/suite_uninstall/tasks/main.yml
  ibm/mas_devops/roles/suite_uninstall/templates/wipe-mongo-data.sh.j2
Labels: Enhancement
