Repository ibm-mas/ansible-devops, pull requests merged in 2024-08, with the labels that each got.

#1402 [patch] replace deprecated "graph" type with "timeseries" and update the mongo isprimary query on the mongo dashboard
  ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka-exporter.json
  ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka-zookeeper.json
  ibm/mas_devops/roles/kafka/templates/redhat/grafana-json/kafka.json
  ibm/mas_devops/roles/mongodb/templates/community/dashboards/json/mongodb-overview-grafana.json
Labels: Improvement/Tweak

#1422 [patch] fix gpu-operator-certified mirror error by using default v24.6 channel
  ibm/mas_devops/roles/mirror_ocp/templates/imagesetconfiguration.yml.j2
Labels: Bug Fix

#1428 [patch] Fix DB2 logs/backup/temps/storage optionally condition
  ibm/mas_devops/roles/db2/README.md
  ibm/mas_devops/roles/db2/templates/db2ucluster.yml.j2
Labels: Bug Fix

#1429 [patch] Add MAS_APP_SETTINGS_DB_SCHEMA as alt for MAS_APP_SETTINGS_DB2_SCHEMA
  docs/playbooks/oneclick-manage.md
  ibm/mas_devops/playbooks/oneclick_add_manage.yml
  ibm/mas_devops/roles/suite_app_config/README.md
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/health.yml
  ibm/mas_devops/roles/suite_app_config/vars/defaultspecs/manage.yml
  ibm/mas_devops/roles/suite_app_config/vars/health.yml
  ibm/mas_devops/roles/suite_app_config/vars/manage.yml
Labels: Improvement/Tweak

#1418 [patch] Support OCP version aliases
  ibm/mas_devops/roles/ocp_provision/README.md
  ibm/mas_devops/roles/ocp_provision/defaults/main.yml
  ibm/mas_devops/roles/ocp_provision/tasks/main.yml
Labels: Improvement/Tweak

#1414 [patch] Rename AI Broker role variables for consistency
  docs/playbooks/oneclick-aibroker.md
  ibm/mas_devops/playbooks/oneclick_add_aibroker.yml
  ibm/mas_devops/roles/aibroker/README.md
  ibm/mas_devops/roles/aibroker/tasks/apikey/main.yml
  ibm/mas_devops/roles/aibroker/tasks/s3/install/main.yml
  ibm/mas_devops/roles/aibroker/tasks/s3/main.yml
  ibm/mas_devops/roles/aibroker/tasks/s3/remove/main.yml
  ibm/mas_devops/roles/aibroker/tasks/watsonx/install/main.yml
  ibm/mas_devops/roles/aibroker/tasks/watsonx/main.yml
  ibm/mas_devops/roles/aibroker/vars/main.yml
  ibm/mas_devops/roles/kmodels/README.md
  ibm/mas_devops/roles/kmodels/tasks/main.yml
  ibm/mas_devops/roles/kmodels/templates/kmodels-controller/configmap.yml.j2
  ibm/mas_devops/roles/kmodels/templates/kmodels-store/configmap.yml.j2
  ibm/mas_devops/roles/kmodels/vars/main.yml
  ibm/mas_devops/roles/odh/README.md
  ibm/mas_devops/roles/odh/tasks/main.yml
  ibm/mas_devops/roles/odh/tasks/pipeline-operator.yml
  ibm/mas_devops/roles/odh/templates/odh/dspa-aws.yml.j2
  ibm/mas_devops/roles/odh/templates/odh/dspa-minio.yml.j2
  ibm/mas_devops/roles/odh/vars/main.yml
Labels: Improvement/Tweak

#1431 [patch] Add MASBR_ACTION to Cronjob env
  ibm/mas_devops/common_tasks/backup_restore/create_run_tasks_job.yml
Labels: Bug Fix

#1412 [minor] Add "Special Characters" support to MAS install
  ibm/mas_devops/roles/suite_install/README.md
  ibm/mas_devops/roles/suite_install/defaults/main.yml
  ibm/mas_devops/roles/suite_install/templates/core_v1_suite.yml.j2
Labels: Enhancement

#1410 [minor] Support August catalog
  build/bin/build-collection.sh
  ibm/mas_devops/common_vars/casebundles/v9-240827-amd64.yml
Labels: Catalog Update

#1438 [patch] Add Red Hat catalog prefix
  ibm/mas_devops/roles/ocp_contentsourcepolicy/README.md
  ibm/mas_devops/roles/ocp_contentsourcepolicy/defaults/main.yml
  ibm/mas_devops/roles/ocp_contentsourcepolicy/templates/redhat-catalogs.yml.j2
Labels: Improvement/Tweak

#1440 [patch] Patch the ibmcloud-block-storage-driver DaemonSet
  ibm/mas_devops/roles/ocp_verify/defaults/main.yml
  ibm/mas_devops/roles/ocp_verify/tasks/main.yml
Labels: Improvement/Tweak
