Repository ibm-mas/ansible-devops, pull requests merged in 2025-08, with the labels that each got.

#1864 [patch] sanitize ocp_version input for roks
  ibm/mas_devops/roles/ocp_provision/tasks/providers/roks/provision_roks.yml
Labels: Improvement/Tweak

#1863 [patch] add check while applying dro pvc
  ibm/mas_devops/roles/dro/tasks/install-dro/main.yml
Labels: Bug Fix

#1861 [minor] Support August Catalog Update
  build/README.md
  ibm/mas_devops/roles/db2/tasks/install/main.yml
  ibm/mas_devops/roles/db2/tasks/upgrade/run-db2-instances-upgrade.yml
Labels: Catalog Update
